### ISSUE TITLE
Transactions and sessions

### ISSUE THREAD

**Issue by johnknoop** [piotr-rojek/devopsifyme-sbemulator#8]
Really good initiative! Unfortunately in our case we need support for both transactions (sending messages within a TransactionScope) and sessions. Is this something you'll be implementing at some point?

**Comment by piotr-rojek** [comment]
Thanks! I do not know when I will have the time to look at this, but I understand that RabbitMQ does not support transactions and sessions. This means that to support transactions, we would have to implement ActiveMQ as a backend. The implementation is straightforward for most of it (replace RabbitMQ client library with ActiveMQ one), but it requires some time to write ;) I would be happy to assist if you are willing to contribute some code. Otherwise, I will let you know when and if I get to it myself ;)

**Comment by piotr-rojek** [comment]
not planned atm
